### ISSUE TITLE
Allow intercepting the stdout/stderr for processing

### ISSUE THREAD

**Issue by josegonzalez** [alexellis/go-execute#12]
It would be great if we could define a way to manipulate stdout/stderr as it is being streamed.

## Expected Behaviour
I would like to do something like the following:

```shell
mangler := func (line string) (string, bool) {
    return fmt.Sprintf("        %s", line), true
}
cmd := execute.ExecTask{
    Command:     "docker",
    Args:        []string{"version"},
    StdoutFunc: mangler,
    StderrFunc: mangler,
}
```

This would prepend the line _before_ it is output. The second argument would be a boolean controlling whether the line should be output or not (true == print, false == don't print).

This would allow me to redact content _or_ wrap it to improve the output for a CLI tool.

## Current Behaviour

At the moment, you can either stream the output as is or you can capture all the output and mangle it at the end. Neither is quite satisfactory.

## Possible Solution

Not sure how I'd implement this. The simplest way is maybe to allow passing in a `Writer` that you would set on `cmd.Stdout` and a separate one for `cmd.Stderr`, but not sure of what side effects that might have.

## Steps to Reproduce (for bugs)

N/A

## Context

I'm writing a [tool](https://github.com/dokku/lambda-builder) that allows me to build lambda functions locally and one step I'd like to do is build a test docker image that folks can use to play with the built lambda locally in an env similar to what is available on AWS. The output for the `docker build` call looks silly to me though and I'd like to indent it to match how the rest of the output looks.

## Your Environment

* `go version` : go version go1.17.9 darwin/amd64

* Operating System and version (e.g. Linux, Windows, MacOS): macOS Monterey 12.3.1

* Link to your project or a code example to reproduce issue: https://github.com/dokku/lambda-builder

**Comment by josegonzalez** [comment]
Coming back to this since I have a desire to do this again :D

For this, could we do something like:

```go
stdoutWriters := []io.Writer{&stdoutBuff}
stderrWriters := []io.Writer{&stderrBuff}

if et.StreamStdio {
	stdoutWriters = append(stdoutWriters, os.Stdout)
	stderrWriters = append(stdoutWriters, os.Stderr)
}

if et.Stdout != nil {
	stdoutWriters = append(stdoutWriters, et.Stdout)
}

if et.Stderr != nil {
	stderrWriters = append(stderrWriters, et.Stdout)
}

cmd.Stdout = io.MultiWriter(stdoutWriters...)
cmd.Stderr = io.MultiWriter(stderrWriters...)
```

This would be bc-compatible I think and would allow one to disable the existing streaming and add their own version.

Thoughts?

**Comment by alexellis** [comment]
@LucasRoesler cc
