### ISSUE TITLE
Args are ignored in shell mode

### ISSUE THREAD

**Issue by Patazerty** [alexellis/go-execute#2]
Sorry to bother you again with this bug but I don't think the current behavior is expected.

When setting `Shell: True` and settings arguments, either in the `Command` field or the `Args` field, args are not taken into account.

## Expected Behaviour
Using the readme example that should list files in the $HOME directory with the `-l` option specified. It should returns the list of files in $HOME just like a `/bin/sh -c "ls -l $HOME"` command would.

## Current Behaviour
Args are ignored and the readme example executes the `ls` without the `-l` option.

## Possible Solution
Don't split the args but join them to form only 3 exec args: `/bin/bash`, `-c` and `ls -l`

## Steps to Reproduce (for bugs)
Build the example code in the readme and execute it 

## Context
I was simply writing unit tests for the exit code check feature and could not get a `ls /file_that_does_not_exists` to actually execute it in shell mode with the arg.

## Your Environment
* `go version go1.13.1 linux/amd64`

**Comment by alexellis** [comment]
Please can you go ahead with the plan I outlined of creating a V2 package?

**Comment by alexellis** [comment]
See what you think of https://github.com/alexellis/go-execute/releases/tag/0.2.1

As I have said a couple of times already, there are two important upstream clients that depend on this behaviour, we cannot break that contract.

**Comment by alexellis** [comment]
Args handling in shell mode has now been fixed, but what hasn't been changed is setting an error with exit-code non 0, because it's technical not what the error is being used for in the API.

Error - unable to fork
Non-zero exit code = non-zero exit code

**Comment by alexellis** [comment]
Let me know if there's anything else you need. You mentioned k3sup, this version has also been re-vendored there.

**Comment by Patazerty** [comment]
Thanks a lot ! This does allow k3sup to not keep going executing commands that failed but requires a change in k3sup, will open an issue about that there.
