### ISSUE TITLE
GoDoc link on readme returns 404

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/go-execute#3]
The link on readme to the godoc site returns a 404
## Expected Behaviour

a godoc page
## Current Behaviour

404
## Steps to Reproduce (for bugs)

1. follow link in readme that points to godoc

**Comment by alexellis** [comment]
Please feel free to fix

**Comment by viveksyngh** [comment]
This is fixed now.

**Comment by Waterdrips** [comment]
/close
:+1:

**Comment by alexellis** [comment]
Feel free to add a direct file here that redirects to openfaas/faas.
