### ISSUE TITLE
Passing in string quoted arg with spaces gets split into multiple args

### ISSUE THREAD

**Issue by Waterdrips** [alexellis/go-execute#4]
Theres an open issue https://github.com/openfaas-incubator/ofc-bootstrap/issues/16 here that is caused by the handling of quoted args in the execute command.

In a normal command the things in quotes with spaces get passed as part of the same arg, it appears as though they get split here.

Is there something we can do to allow this type of behaviour?

## Expected Behaviour

if we pass this ` --from-literal=github-webhook-secret="some space seperated secret"` as a single arg  it should be treated as one on execute. 
## Current Behaviour

This is the command as printed to the console, but this gets split on the spaces rather than being taken as a single input.
`exec:  kubectl create secret generic -n openfaas-fn github-webhook-secret --from-literal=github-webhook-secret="some space seperated secret" `

Error: `{ error: exactly one NAME is required, got 4}`
## Steps to Reproduce (for bugs)

1. create a command with an arg that has a quoted string
2.run the command
3.it will fail as its split on spaces

## Context

ofc-bootstrap tool (issue linked above) has an issue with creating secrets that have spaces in them, as we build kubectl commands to generate secrets. If one of these is quoted, but has spaces then it fails.

## Your Environment

* `go version` 
go version go1.12.6 darwin/amd64
* Operating System and version (e.g. Linux, Windows, MacOS):
Darwin heyal 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
* Link to your project or a code example to reproduce issue:
Theres an open issue https://github.com/openfaas-incubator/ofc-bootstrap/issues/16 here that is caused by the handling of quoted args in the execute command.

**Comment by alexellis** [comment]
Generally the `Args: []string{}` option needs to be used for this, and the command should only include the root executable. Do you want to work on a fix @Waterdrips ?

**Comment by alexellis** [comment]
I mean in ofc-bootstrap
