### ISSUE TITLE
How to implement pipes?

### ISSUE THREAD

**Issue by g14a** [alexellis/go-execute#6]
Hello!
     If I want to execute a command like `history | head -1` how do I implement it using this package?

Regards

**Comment by alexellis** [comment]
Hi, I think you'll need to do this in code. Start your first process. Then hook up its streams to the second and so forth. 

It's not something that I have included in the docs and may not be possible with this library, you may need to go back to stdlib.

**Comment by alexellis** [comment]
Let me know how you get on?

**Comment by g14a** [comment]
My use case was to find the last used linux command. But that would be impossible even with stdlib because `history` is a shell builtin and not a linux binary. So I withdrew my plan of implementing it. However I was able to run `git` commands with `go-execute` successfully so thank you for that! :grinning: I'll remember to put something here in the future if I get it working through some way.
