### ISSUE TITLE
Adding a simple check to variable "Command"

### ISSUE THREAD

**Issue by leewei05** [alexellis/go-execute#8]
Hi, just found this interesting project. I would like to start to contribute as my first open source project. 😄
I've run through the code and had some ideas for this project.

I have also noticed you said there are upstream projects that heavily depend on this repository.
Due to that reason, I think I can start working on some small features or refactoring, without changing the main function of it.

As I mentioned in the title, I think we can add a simple check on the `Command` variable for the `ExecTask` struct.
Handling null cases and return error early before structuring the commands and args.

Let me know what you think, and maybe throw out some of your thoughts about new features that I can work on. 👍

**Comment by alexellis** [comment]
Hi @leewei05 

I would appreciate a blog post on how to use the library with examples. Would you be open to that?

As for the suggested refactoring, I don't see the value in that at this time. Having said that, I would welcome your contributions to other projects I maintain. If you would like to work on issues on other repos join us on Slack https://slack.openfaas.io/

Alex
